### ISSUE TITLE
Firefox Accounts l10n content on staging not up to date

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#320]
@rfk Our localizer @jordis reported that the dev site has not been up to date to reflect what's translated in Pontoon. https://pontoon.mozilla.org/ca/firefox-accounts/.  This is what we have on Pontoon for the FxA project: https://pontoon.mozilla.org/projects/firefox-accounts/info/. Has the info changed or do we have a sync issue?

**Comment by rfk** [comment]
Thanks @peiying2, I'm going to defer to @shane-tomlinson here who is the lead engineer on FxA these days.

**Comment by shane-tomlinson** [comment]
@peiying2, @jordis - which dev site? I can have a look, but want to look at the same thing as you.

**Comment by shane-tomlinson** [comment]
Doh, staging.

**Comment by shane-tomlinson** [comment]
https://accounts.stage.mozaws.net/ver.json

```json
{
  "commit": "a0249ac4a1a5627a62c1fb8cc904670bae7e7fe5",
  "version": "1.128.1",
  "l10n": "fd2e4d67f7ef582f1154d73e2342c6caa22bda18",
  "tosPp": "7620b391f9473d41a70f2c9226469073025fc6fe",
  "source": "https://github.com/mozilla/fxa-content-server"
}
```

That l10n commit is from 12 days ago:

https://github.com/mozilla/fxa-content-server-l10n/commit/fd2e4d67f7ef582f1154d73e2342c6caa22bda18

This makes sense. The git SHA for the strings is chosen a few days before the deployment so that a full prod-like stack can be tested end to end. The train-128 deployment was scheduled for Jan 14th, Jan 10th was the Thursday before it, which would have given the Thursday/Friday and weekend to test.

Today is the train-129 tag so any strings updated after Jan 10th will be on stage within the next few days.

https://stable.dev.lcip.org integrates string changes more frequently:

```json
{
  "commit": "d28a13fd3d2ad4c2b4b95ee664e64a84f740e493",
  "version": "1.128.1",
  "l10n": "ba20bf25b35acea4fa880d8c726d5b9c405c0273",
  "tosPp": "7620b391f9473d41a70f2c9226469073025fc6fe",
  "source": "https://github.com/mozilla/fxa-content-server"
}
```

The git SHA used there is from Jan 15th. Not fully up to date, but closer.

@jrgm is this an accurate representation of how you pull in strings? Do the strings on stable auto-update?

**Comment by shane-tomlinson** [comment]
@jrgm to investigate why stable didn't pull in the new strings on Thursday.

**Comment by shane-tomlinson** [comment]
It *did*. On Thursday @ 4pm Pacific. Closing.

**Comment by jordis** [comment]
This issue is closed but I cannot see the localized strings in the staging server https://latest.dev.lcip.org/
All strings are in English. Is this working as designed?
