### ISSUE TITLE
[be]: Localized content not shown on production

### ISSUE THREAD

**Issue by peiying2** [mozilla/fxa-content-server-l10n#364]
@shane-tomlinson Our Belarusian localizer reported that his work has not shown up on production despite completing it more than a month ago: https://accounts.firefox.com/. When he switches to `uk` (Ukrainian) as the preferred language, it works. However when he switches to `be` as the preferred language, the localized content doesn't show up.

**Comment by shane-tomlinson** [comment]
We only enable locales when we are told they are ready, there is nothing automatic about the process. `be` is not on the [list of supported locales](https://github.com/mozilla/fxa/blob/24bd5c48e364452f346ff9dace9815390536611c/packages/fxa-shared/l10n/supportedLanguages.json#L5), I'm not sure if it was never enabled, or if it was once enabled and we later disabled it. Can you let us know when new locales are ready, otherwise we don't know. I'll open a PR to enable `be`.

**Comment by peiying2** [comment]
> We only enable locales when we are told they are ready, there is nothing automatic about the process. `be` is not on the [list of supported locales](https://github.com/mozilla/fxa/blob/24bd5c48e364452f346ff9dace9815390536611c/packages/fxa-shared/l10n/supportedLanguages.json#L5), I'm not sure if it was never enabled, or if it was once enabled and we later disabled it. Can you let us know when new locales are ready, otherwise we don't know. I'll open a PR to enable `be`.

Didn't know it was not supported. It is 100% complete: https://pontoon.mozilla.org/be/firefox-accounts/. Thanks so much!!
