### ISSUE TITLE
automate string extraction

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server-l10n#39]
Currently, string extraction is a manual process as outlines in #35. This is prone to user error and could be scripted to a large extent. A simple grunt or bash script to extract the strings from both the content server and auth mailer would be useful. 

Ref #35

**Comment by pdehaan** [comment]
I think it should be pretty easy to automate the extraction script w/ Grunt+bash (I'm a fan of [**grunt-shell**](https://github.com/sindresorhus/grunt-shell), fwiw). Not sure what repo it should live in (I assume fxa-content-server-l10n, if that's where we'd be doing the `git { add | commit | push }` from.
The one tricky gotcha would be that it actually bridges 3ish repos, so ~~anybody~~ everybody running the extract script would need to have consistent folder structures (or we get clever with adding paths to sister repos in the convict config and people can override in their local.json config files).

The other part I wouldn't touch is automating the git commit + push stuff. We could probably have the Grunt task spit out the 3-4 git commands to create a new branch and then do a `git commit -am "message"` and then do a git push with the correct train name. Otherwise we would probably want to get overly tricky and prompt the user for a train number so we can automatically create the branch name, blah blah blah...

**Comment by rfk** [comment]
I'm pretty sure we can close this out thanks to @eoger's recent automation; can you please confirm and close this out if everything noted here is now covered?

**Comment by vladikoff** [comment]
Yeap!
