### ISSUE TITLE
Set Language: to sr_Latn for locale sr_Latn

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-content-server-l10n#44]
https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/sr_Latn/LC_MESSAGES/server.po#L9 is anomalous in that the local is `sr_Latn`, but the `Language:` is `sr`. That is not consistent with other locales like `zh_CN`, `zh_TW`, `pt_BR`, `nb_NO`.

**Comment by vladikoff** [comment]
@zaach ping

What should we do here?

**Comment by vladikoff** [comment]
I will talk to @zaach about this one

**Comment by jrgm** [comment]
My understanding is that sr_Latn is an automatic transilteration from Cyrillic to Latin characters. So, the question is, what tool does that transliteration.

**Comment by vladikoff** [comment]
Ok that makes sense, I manually fixed in commit: https://github.com/mozilla/fxa-content-server-l10n/commit/2c20cc8e9c0e682422ae669f6a58dd901584408d

@mathjazz we are not sure if this was automated or not, if it is then the tool that automates it needs a fix to set `sr` to `sr_Latn` if it is the Latin version of `sr` translations

**Comment by mathjazz** [comment]
@Adding @flodolo to comment on how the script actually works.

**Comment by flodolo** [comment]
For this project I file PRs manually but transliteration is done with a script.
Marketplace projects do that automatically. If we could have that, it would be great.

You should find all the information in 
https://bugzilla.mozilla.org/show_bug.cgi?id=1168488
